---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyter-iaa
  namespace: jupyter-iaa
spec:
  interval: 5m0s
  url: https://hub.jupyter.org/helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyter-iaa
  namespace: jupyter-iaa
spec:
  interval: 5m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: jupyter-iaa
            spec:
              template:
                spec:
                  volumes:
                    - name: vault-secrets
                      csi:
                        driver: secrets-store.csi.k8s.io
                        readOnly: true
                        volumeAttributes:
                          secretProviderClass: "jupyter-iaa-credentials"
                  containers:
                    - name: jupyter-iaa
                      env:
                      - name: CLIENTSECRET
                        valueFrom:
                          secretKeyRef:
                            name: jupyter-iaa-k8s-secret
                            key: oauthclientsecret
  chart:
    spec:
      chart: jupyterhub
      version: '2.0.0'
      sourceRef:
        kind: HelmRepository
        name: jupyter-iaa
        namespace: jupyter-iaa
      interval: 1m
  values:
    replicaCount: 1
    serviceAccount:
      enabled: true
      name: jupyter-iaa-vault
    podAnnotations:
      "secrets-store.csi.k8s.io/managed": "true"
